server:
  port: 8080
eureka:
  client:
    service-url:
        defaultZone: '${EUREKA_URI:http://localhost:8761/eureka}'

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 20KB
  application:
    name: blog-gateway-service
  cloud:
    gateway:
      routes:
        - id: blog-web-app
          uri: lb://blog-web-app
          predicates:
            - Path=/web-app/**
          filters:
            - StripPrefix=1
        - id: blog-auth-service
          uri: lb://blog-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
ribbon:
  ReadTimeout: 90000
  ConnectTimeout: 90000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000